"""
acronymes.py — Dictionnaire des acronymes métier de l'Éducation Nationale

Ce fichier liste les abréviations courantes dans les saisines.
Il peut être utilisé pour enrichir les textes avant classification
(remplacer "AESH" par "Accompagnant des Élèves en Situation de Handicap")
ou simplement pour l'affichage dans le dashboard.

Source : reproduit depuis EDN1/back/projet/acronymes.py (sans modification)
"""

ACRONYMES = {
    "AC": "Administration centrale",
    "AEPE": "Accompagnants éducatifs petite enfance",
    "AESH": "Accompagnant des Élèves en Situation de Handicap",
    "ALD": "Affection longue durée",
    "AMI": "Amiens",
    "APE": "Association de Parents d'Élèves",
    "APF": "Association des Paralysés de France",
    "APL": "Aide Personnalisée au Logement",
    "ARE": "Allocation de retour à l'emploi",
    "ASH": "Adaptation Scolaire et Scolarisation des élèves Handicapés",
    "ASSR": "Attestation Scolaire de Sécurité Routière",
    "ATP": "Affectation à titre provisoire",
    "ATSEM": "Agent Territorial Spécialisé des Écoles Maternelles",
    "AUC": "Aucun (dans la colonne caractère)",
    "AXM": "Aix-Marseille",
    "BEP": "Brevet d'Études Professionnelles",
    "BES": "Besançon",
    "BOE": "Bénéficiaire de l'obligation d'emploi",
    "BOR": "Bordeaux",
    "BP": "Brevet professionnel",
    "BTS": "Brevet de Technicien Supérieur",
    "BVS": "Bureau vie scolaire",
    "CA": "Conseil d'administration",
    "CAER": "Concours d'accès à l'échelle de rémunération",
    "CAF": "Caisse d'allocations familiales",
    "CAMSP": "Centre d'Action Médico-Sociale Précoce",
    "CAP": "Certificat d'Aptitude Professionnelle",
    "CAPEPS": "Certificat d'Aptitude au Professorat d'Éducation Physique et Sportive",
    "CASNAV": "Centre Académique pour la Scolarisation des Nouveaux Arrivants",
    "CASU": "Conseiller d'administration scolaire et universitaire",
    "CD": "Conseil de discipline",
    "CDD": "Contrat à Durée Déterminée",
    "CDI": "Centre de Documentation et d'Information",
    "CE": "Chef d'établissement",
    "CET": "Compte épargne temps",
    "CFA": "Centre de Formation des Apprentis",
    "CIO": "Centre d'information et d'orientation",
    "CLD": "Congé longue durée",
    "CLE": "Clermont-Ferrand",
    "CLM": "Congé longue maladie",
    "CM": "Congé maladie",
    "CNED": "Centre national d'enseignement à distance",
    "COP": "Conseiller d'orientation psychologue",
    "CPE": "Conseiller Principal d'Éducation",
    "CPF": "Compte personnel de formation",
    "CPGE": "Classe Préparatoire aux Grandes Écoles",
    "CRE": "Créteil",
    "CROUS": "Centre régional des œuvres universitaires et scolaires",
    "CVEC": "Contribution à la vie étudiante et de campus",
    "DASEN": "Directeur académique des services de l'éducation nationale",
    "DDD": "Défenseur des droits",
    "DIJ": "Dijon",
    "DNB": "Diplôme national du brevet",
    "DSE": "Dossier social étudiant",
    "EAF": "Épreuve anticipée de français (en 1ère)",
    "EDT": "Emploi du temps",
    "EN": "Éducation nationale",
    "ENT": "Environnement numérique de travail",
    "EPLE": "Établissement public local d'enseignement",
    "EPS": "Éducation Physique et Sportive",
    "GRE": "Grenoble",
    "GUA": "Guadeloupe",
    "GUY": "Guyane",
    "HAN": "Handicap",
    "HAR": "Harcèlement",
    "HPI": "Haut Potentiel Intellectuel",
    "IA": "Inspecteur d'académie",
    "IDV": "Indemnité de départ volontaire",
    "IEN": "Inspecteur de l'Éducation Nationale",
    "IME": "Institut médico éducatif",
    "IPR": "Inspecteur pédagogique régional",
    "IUT": "Institut universitaire de technologie",
    "LIL": "Lille",
    "LIM": "Limoges",
    "LP": "Lycée professionnel",
    "LYO": "Lyon",
    "MAR": "Martinique",
    "MDPH": "Maison Départementale des Personnes Handicapées",
    "MEN": "Ministère de l'Éducation Nationale",
    "MON": "Montpellier",
    "NAN": "Nantes",
    "NAT": "National (pôle de médiation)",
    "NCY": "Nancy-Metz",
    "NIC": "Nice",
    "NOR": "Normandie",
    "ORL": "Orléans-Tours",
    "PAI": "Projet d'Accueil Individualisé",
    "PAP": "Plan d'Accompagnement Personnalisé",
    "PAR": "Paris",
    "PIAL": "Pôle Inclusif d'Accompagnement Localisé",
    "POI": "Poitiers",
    "REI": "Reims",
    "REL": "Relationnel (problème)",
    "REN": "Rennes",
    "REP": "Réseau d'éducation prioritaire",
    "REU": "La Réunion",
    "RH": "Ressources humaines",
    "RQTH": "Reconnaissance de travailleur handicapé",
    "SESSAD": "Service d'Éducation Spéciale et de Soins À Domicile",
    "STR": "Strasbourg",
    "TA": "Tribunal administratif",
    "TOU": "Toulouse",
    "TZR": "Titulaire zone de remplacement",
    "ULIS": "Unité Localisée pour l'Inclusion Scolaire",
    "VAE": "Validation des acquis de l'expérience",
    "VER": "Versailles",
}

# Codes/abréviations identifiés comme du bruit (pas de sens métier)
ACRONYMES_BRUIT = {
    "AAA", "AR", "AU", "BBB", "BBBB", "BIJ", "BK", "CDRH", "CLUG", "COR", "CZABAJ",
    "DJ", "DO", "EE", "EEE", "EIJ", "EM", "FF", "FP", "GA", "GGGG",
    "II", "JJJ", "KKK", "LLL", "LLLL", "LRRR", "MK", "MMM", "NNN", "NNNN", "OU",
    "PC", "PCN", "PPP", "PPPP", "RRRR", "RV", "SAB", "SAE", "SSSS", "TS", "TTT",
    "TTTT", "UUU", "UUUU", "VN", "VVV", "XXX", "XXXX", "YYY", "YYYY", "ZZZ"
}
